export const BLOCKS = [
  { type: 'text', label: 'Text', category: 'content', html: `<p data-es-block="text" style="margin:0 0 16px;font-size:15px;line-height:1.6;color:#374151;">Write your paragraph here. You can personalize with {{first_name}}.</p>` },
  { type: 'heading', label: 'Heading', category: 'content', html: `<h1 data-es-block="heading" style="margin:0 0 12px;font-size:24px;line-height:1.3;color:#111827;">Heading</h1>` },
  { type: 'image', label: 'Image', category: 'content', html: `<img data-es-block="image" src="" alt="Image" width="560" style="display:block;width:100%;max-width:560px;height:auto;border:0;" />` },
  { type: 'button', label: 'Button', category: 'content', html: `<table data-es-block="button" role="presentation" border="0" cellpadding="0" cellspacing="0" style="margin:16px 0;"><tr><td style="background:#4f46e5;border-radius:6px;"><a href="https://example.com" style="display:inline-block;padding:12px 24px;color:#ffffff;text-decoration:none;font-weight:600;font-family:Arial,sans-serif;">Call to action</a></td></tr></table>` },
  { type: 'divider', label: 'Divider', category: 'layout', html: `<hr data-es-block="divider" style="border:none;border-top:1px solid #e5e7eb;margin:24px 0;" />` },
  { type: 'spacer', label: 'Spacer', category: 'layout', html: `<div data-es-block="spacer" style="height:24px;line-height:24px;font-size:24px;">&nbsp;</div>` },
  { type: 'cols1', label: '1 column', category: 'layout', html: `<table data-es-block="cols1" role="presentation" width="100%" border="0" cellpadding="0" cellspacing="0"><tr><td style="padding:8px;">Column content</td></tr></table>` },
  { type: 'cols2', label: '2 columns', category: 'layout', html: `<table data-es-block="cols2" role="presentation" width="100%" border="0" cellpadding="0" cellspacing="0"><tr><td width="50%" style="padding:8px;vertical-align:top;">Left column</td><td width="50%" style="padding:8px;vertical-align:top;">Right column</td></tr></table>` },
  { type: 'cols3', label: '3 columns', category: 'layout', html: `<table data-es-block="cols3" role="presentation" width="100%" border="0" cellpadding="0" cellspacing="0"><tr><td width="33%" style="padding:8px;vertical-align:top;">One</td><td width="33%" style="padding:8px;vertical-align:top;">Two</td><td width="33%" style="padding:8px;vertical-align:top;">Three</td></tr></table>` },
  { type: 'header', label: 'Header', category: 'chrome', html: `<div data-es-block="header" style="padding:20px 0;text-align:center;"><span style="font-size:20px;font-weight:700;color:#111827;letter-spacing:1px;">Brand</span></div>` },
  { type: 'logo', label: 'Logo', category: 'chrome', html: `<div data-es-block="logo" style="text-align:center;padding:16px 0;"><img src="" alt="Logo" width="140" style="display:inline-block;max-width:140px;height:auto;border:0;" /></div>` },
  { type: 'nav', label: 'Navigation', category: 'chrome', html: `<table data-es-block="nav" role="presentation" width="100%" border="0" cellpadding="0" cellspacing="0"><tr><td align="center" style="padding:8px;font-family:Arial,sans-serif;font-size:13px;"><a href="#" style="color:#4f46e5;text-decoration:none;padding:0 10px;">Home</a><a href="#" style="color:#4f46e5;text-decoration:none;padding:0 10px;">Shop</a><a href="#" style="color:#4f46e5;text-decoration:none;padding:0 10px;">Account</a></td></tr></table>` },
  { type: 'social', label: 'Social links', category: 'chrome', html: `<div data-es-block="social" style="text-align:center;padding:12px 0;font-family:Arial,sans-serif;font-size:13px;"><a href="https://twitter.com" style="color:#4f46e5;margin:0 8px;">Twitter</a><a href="https://linkedin.com" style="color:#4f46e5;margin:0 8px;">LinkedIn</a><a href="https://instagram.com" style="color:#4f46e5;margin:0 8px;">Instagram</a></div>` },
  { type: 'quote', label: 'Quote', category: 'content', html: `<blockquote data-es-block="quote" style="margin:16px 0;padding:12px 16px;border-left:3px solid #4f46e5;color:#4b5563;font-style:italic;">A short customer quote goes here.</blockquote>` },
  { type: 'product', label: 'Product card', category: 'content', html: `<table data-es-block="product" role="presentation" width="100%" border="0" cellpadding="0" cellspacing="0" style="border:1px solid #e5e7eb;margin:12px 0;"><tr><td style="padding:16px;font-family:Arial,sans-serif;"><img src="" alt="Product" width="100%" style="display:block;width:100%;height:auto;border:0;" /><h3 style="margin:12px 0 6px;font-size:16px;color:#111827;">Product name</h3><p style="margin:0 0 12px;color:#6b7280;font-size:14px;">Short description</p><strong style="color:#111827;">$49.00</strong></td></tr></table>` },
  { type: 'cta', label: 'CTA banner', category: 'content', html: `<div data-es-block="cta" style="background:#111827;color:#ffffff;padding:32px 24px;text-align:center;font-family:Arial,sans-serif;"><h2 style="margin:0 0 8px;font-size:22px;">Ready to get started?</h2><p style="margin:0 0 16px;color:#d1d5db;">Join thousands of teams already shipping better email.</p><a href="https://example.com" style="display:inline-block;background:#4f46e5;color:#ffffff;text-decoration:none;padding:12px 24px;border-radius:6px;font-weight:600;">Start now</a></div>` },
  { type: 'footer', label: 'Footer', category: 'chrome', html: `<div data-es-block="footer" style="padding:24px 8px;text-align:center;color:#9ca3af;font-size:12px;font-family:Arial,sans-serif;"><p style="margin:0 0 8px;">Sent by Acme Inc. · 123 Market Street</p><a href="#" style="color:#6b7280;">Unsubscribe</a></div>` },
  { type: 'legal', label: 'Legal / unsubscribe', category: 'chrome', html: `<div data-es-block="legal" style="padding:16px;text-align:center;color:#9ca3af;font-size:11px;font-family:Arial,sans-serif;"><p style="margin:0 0 6px;">You received this email because you subscribed to updates.</p><a href="#" style="color:#6b7280;">Unsubscribe</a> · <a href="#" style="color:#6b7280;">Preferences</a> · <a href="#" style="color:#6b7280;">Privacy</a></div>` },
  { type: 'html', label: 'Custom HTML', category: 'advanced', html: `<div data-es-block="html" data-es-custom="1"><!-- custom html --><p>Custom HTML block — source is preserved.</p></div>` },
];

export function blockByType(type) {
  return BLOCKS.find((b) => b.type === type);
}
