export const state = {
  needsSetup: true,
  user: null,
  view: 'projects',
  projects: [],
  folders: [],
  project: null,
  saveState: 'saved',
  mode: 'code',
  paneTab: 'html',
  device: 'desktop',
  customWidth: 600,
  zoom: 1,
  clientSkin: 'none',
  fullscreenPreview: false,
  generated: null,
  compatibility: [],
  doctor: null,
  accounts: [],
  gmailConfigured: false,
  assets: [],
  history: [],
  templates: [],
  templateCategories: [],
  settings: {},
  sendDefaults: {},
  storage: null,
  selectedElement: null,
  visualHistory: [],
  visualHistoryIndex: -1,
  contacts: [],
  scheduled: [],
  versions: [],
  links: [],
  outputView: 'converted',
  formatOnSave: true,
};

export function set(partial) {
  Object.assign(state, partial);
}
